export const ActionTypes = {
    LOADER_ON: 'LOADER_ON',
    LOADER_OFF: 'LOADER_OFF',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    SET_ALL_WORKSPACE_INFO: 'SET_ALL_WORKSPACE_INFO',
    SET_WORKSPACE_INFO_UNDEFINED: 'SET_WORKSPACE_INFO_UNDEFINED',
    SET_SELECTED_WORKSPACE:'SET_SELECTED_WORKSPACE',
    SET_SELECTED_WORKSPACE_UNDEFINED:'SET_SELECTED_WORKSPACE_UNDEFINED',
    SET_SELECTED_WORKSPACE_GROUP: 'SET_SELECTED_WORKSPACE_GROUP',
    SET_SELECTED_WORKSPACE_ACCOUNT: 'SET_SELECTED_WORKSPACE_ACCOUNT',
    SET_INVITES_INFO: 'SET_INVITES_INFO',
    SET_INVITES_INFO_UNDEFINED:'SET_INVITES_INFO_UNDEFINED',
}